resolver: lts-13.28
packages:
  - '.'
allow-newer: true
extra-deps:
  - hspec-contrib-0.5.0
  - github: dmalikov/bencoding
    commit: 59b6159d964d395c2992882b2e249f330655bd41
  - github: hstorrent/hstorrent
    commit: 3a8887aaeb7e6239685c0ad5fcf370156c840d25
ghc-options:
  "$locals": -fhide-source-paths
