resolver: lts-7.7

flags: {}
extra-package-dbs: []

packages:
    - '.'
    - location:
        git: https://github.com/hstorrent/hstorrent.git
        commit: 3a8887aaeb7e6239685c0ad5fcf370156c840d25
    - location:
        git: https://github.com/dmalikov/bencoding.git
        commit: c1066e17be04f219dd84c372cf357a34f4c6724e
